- hosts: localhost
  tasks:
  # this will fail the second time the playbook is run since it can't create a folder which already exists
  - name: Set up a task that will fail
    ansible.builtin.command: "mkdir /home/ubuntu/failfolder"
    # we can set up a way of ignoring errors
    ignore_errors: True
  - name: Create a file
    become: True
    copy:
      content: "Spent too long on this"
      dest: /etc/robbieconfig
      mode: '0644'
    # add a register variable, the output of the module will be stored in this
    register: robbietaskvar
  - name: Print a message
    debug:
      msg: "Below is a variable"
  - name:
    debug:
      # var: robbietaskvar
      # we can access specific parts of the variable like a dictionary
      var: robbietaskvar.failed
