name: Run script using actions
#run-name: Run script using actions
on:
  workflow_dispatch: # manual trigger
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Running script file
        working-directory: day-6-7/GitHub-Actions/
        run: bash ./script.sh
