name: Manually print day-7 content
run-name: Manually print day-7 content
on:
  workflow_dispatch:
jobs:
  my_job:
    name: List day-7 repo content
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Print repo content
        working-directory: day-7/
        run: ls -la
