name: Scheduled print of day-7
run-name: Scheduled print of day-7 content
on:
  schedule:
  - cron: "0/5 * * * *"
jobs:
  my_job:
    name: List day-7 repo content
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Print repo content
        working-directory: day-7/
        run: ls -la
